### ISSUE TITLE
What am I missing 

### ISSUE THREAD

**Issue by doofy69** [odsum/TinyChatBot#15]
![tinychatboterror](https://user-images.githubusercontent.com/37122937/37057382-28a1ad82-2155-11e8-8bac-758bdd870495.png)

Recieved this error apon starting the bot client (bot.py) I have updated pip and installed what was required to to run the bot. I currently run another bot but wanted to try this one because it looks as if its been updated. Forgive me if this is an ignorant posting. I'm still learning things, any help would be great, currently Im Running 2.7.10 Thanks. path to python is C:\python27\

**Comment by odsum** [comment]
pip install simplejson

**Comment by doofy69** [comment]
Thank you. I didnt understand the error, but quicjly realized the pipping what u was missing fixed the issue. Thanks for the work youre putting in.
