### ISSUE TITLE
How to autoban/autokick specific words, characters, and long trailing whitespaces.

### ISSUE THREAD

**Issue by AlphicJay** [odsum/TinyChatBot#16]
Hello

First off, very nice bot man. I use it in a room I moderate; however when i asked another mod to use !spam for some reason the guy whose using a spam bot in our room cannot be stopped. His bot uses specific keyboards but i cannot add certain words to autokick list, or is there any way to do this.

Also, is there a way us users can pay and help contribute to this project. I would like to donate, this has been very helpful. Very nice work once again.

**Comment by Technetium1** [comment]
@kiratsuchi which room is being hit? There is a way to spam that can't be prevented without banning everyone that is not verified on their join...
I believe you are looking for `+banword` found here: https://github.com/odsum/TinyChatBot/blob/95d34eb5ceea99317e185d668896225273b5d548/tinybot.py#L598 I just noticed a typo below that for banword removal and have created https://github.com/odsum/TinyChatBot/pull/17 to correct it.

**Comment by AlphicJay** [comment]
The room that is being hit is called "cutieswithbooty". I used the command "!banw pizza" to ban anyone who types pizza but it didnt work. I tried this in chat, and by pming the bot. Both accounts are mods by the way.

**Comment by Technetium1** [comment]
The command to blacklist the word "pizza" would be `!+banword pizza`.

**Comment by AlphicJay** [comment]
Ok thanks. I'll try this right now.

**Comment by toozzb** [comment]
i would like to assist if you pay me, let me know i know how to stop the spammer, you are talkin to the right department if u hit me
