### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by spiderfaced** [odsum/TinyChatBot#19]
Was there ever a solid workaround for the Captcha? I am certain I've seen a script open a browser window to allow you to solve it and then continue running the script.

If you can offer any hints on how I might get this working I would be very appreciative.

**Comment by spiderfaced** [comment]
I've tried changing bot accounts as suggested but I cannot get consistent results for my bot to be moderated.

**Comment by NawtJ0sh** [comment]
You gotta login to the bot account on the browser & solve the captcha, then it should work.

**Comment by spiderfaced** [comment]
Working like a charm so far. Thanks so much :)

**Comment by Technetium1** [comment]
@spiderface There is no option to pop up a webkit window to solve for technical reasons. The only way you can 'solve' it in python is by using a captcha solving api. Adding in a captcha solver is a lot of effort, and would likely contribute to more spam bombing if released.
