### ISSUE TITLE
Issue with running tinybot

### ISSUE THREAD

**Issue by platnium1** [odsum/TinyChatBot#5]
When I attempt to run the tinybot in the command prompt, it says: "python: can't open file 'path\to\bot_.py': [Errno 2] No such file or directory"

How do I go about fixing this?

**Comment by androg55** [comment]
You're supposed to run the PY file that says (bot) Also. Focus on getting Your python client installed correctly. There are a few things You need to install with pip in order to get the python scripts running correctly.

**Comment by platnium1** [comment]
@androg55 sorry, I meant when I type in "python path\to\bot.py" in the command prompt, I get the said message above.

**Comment by platnium1** [comment]
@androg55 

I fixed the issue. Thanks.

**Comment by platnium1** [comment]
However, one last question: Are some of the commands not working on beta?
