### ISSUE TITLE
Bot Logins in but dont mod itself

### ISSUE THREAD

**Issue by Webx123** [odsum/TinyChatBot#8]
you can log in but when logging in with a mod account it dont make the bot mod.... the bot is a regular user but you can view the profile hes logged in correctly guess its not grabbing the mod auth?

**Comment by androg55** [comment]
Having same issues. I'm looking into it.

**Comment by sean-james** [comment]
Any update on what the issue could be?

**Comment by Technetium1** [comment]
The issue is that captcha is not being solved.

**Comment by androg55** [comment]
^

**Comment by xbc4000** [comment]
All LELZ ^^ HAHAHA!!
